# Custom Language File for Launcher Customizer

[ejs.app]
title = "MSMP Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "https://x.com/Monarcas096?t=1BruxpczhrFghVlyocIu4Q&s=09"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/PSNaHRtJjY"

[ejs.settings]
sourceGithubLink = "https://github.com/yOstrix/MSMP"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "MSMP Launcher"
welcomeDescription = "Seja bem vindo ao Launcher do MSMP"
welcomeDescCTA = "Clique e Jogue 🫵."
