# Custom Language File for Launcher Customizer

[ejs.app]
title = "MSMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/yOstrix/MSMP"
mediaTwitterURL = "https://x.com/Monarcas096?t=1BruxpczhrFghVlyocIu4Q&s=09"
mediaInstagramURL = "https://www.instagram.com/msmp__?igsh=c2R0MTB1NnR3ajl1"
mediaYouTubeURL = "https://www.youtube.com/@Someonew-mg2wg#"
mediaDiscordURL = "https://discord.gg/PSNaHRtJjY"

[ejs.settings]
sourceGithubLink = "https://github.com/yOstrix/MSMP"
supportLink = "https://github.com/yOstrix/MSMP/issues"

[ejs.welcome]
welcomeHeader = "MSMP Launcher"
welcomeDescription = "Seja bem vindo ao Launcher do MSMP"
welcomeDescCTA = "Clique e Jogue!"