[ejs.landing]
updateAvailableTooltip = "Atualização Disponível"
usernamePlaceholder = "Nome de usuário"
usernameEditButton = "Editar"
settingsTooltip = "Configurações"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Serviços"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NOTÍCIAS"
launchButton = "JOGAR"
launchButtonPlaceholder = "&#8226; Nenhum servidor Selecionado"
launchDetails = "Por Favor, espere..."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Chegando por novas notícias!"
newsErrorFailedSpan = "Falha ao carregar as notícias!"
newsErrorRetryButton = "Tente novamente!"
newsErrorNoneSpan = "Sem Notícias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "CONTA PIRATA"
loginEmailError = "* Valor Inválido"
loginEmailPlaceholder = "NOME DE USUÁRIO"
loginPasswordError = "* Requer"
loginPasswordPlaceholder = "SENHA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Esqueceu sua senha?"
loginRememberMeText = "Lembre-me"
loginButtonText = "FAZER LOGIN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Não tem uma conta?"
loginPasswordDisclaimer1 = "Your password is sent directly to mojang and never stored."
loginPasswordDisclaimer2 = "{appName} is not affiliated with Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opções de Login"
loginWithMicrosoft = "Logar com Microsoft"
loginWithPirata = "Logar com Pirata"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores Disponíveis"
serverSelectConfirm = "Selecionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecione uma Conta"
accountSelectConfirm = "Selecionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configurações"
navAccount = "Conta"
navMinecraft = "Minha Conta"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Sobre"
navUpdates = "Atualizações"
navDone = "Pronto"
tabAccountHeaderText = "Configurações da Conta"
tabAccountHeaderDesc = "Configure suas contas e opções de login."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Adicionar Conta Microsoft"
mojangAccount = "Pirata"
addMojangAccount = "+ Adicionar Conta Pirata"
minecraftTabHeaderText = "Configurações do Minecraft"
minecraftTabHeaderDesc = "Opções relatadas do launcher."
gameResolutionTitle = "Resolução do Jogo"
launchFullscreenTitle = "Iniciar em Tela Cheia."
autoConnectTitle = "Conectar automaticamente ao servidor."
launchDetachedTitle = "Iniciar em segundo plano."
launchDetachedDesc = "Iniciar o jogo em segundo plano. O launcher continuará a funcionar, mas o jogo não será exibido."
tabModsHeaderText = "Configurações dos Mods"
tabModsHeaderDesc = "Habilitar ou desabilitar mods."
switchServerButton = "Trocar Servidor"
requiredMods = "Mods Necessários"
optionalMods = "Mods Opcionais"
dropinMods = "Jogue os mods aqui"
addMods = "Adicionar Mods"
dropinRefreshNote = "(F5 para Recarregar)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Habilitar ou desabilitar shaders. Por favor, note que shaders só funcionarão suavemente em configurações poderosas. Você pode adicionar pacotes personalizados aqui."
selectShaderpack = "Selecionar Shaderpack"
tabJavaHeaderText = "Configurações do Java"
tabJavaHeaderDesc = "Gerenciar a configuração do Java (avançado)."
memoryTitle = "Memória"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "O mínimo recomendado de RAM é 3 gigabytes. Definir os valores mínimo e máximo para o mesmo valor pode reduzir o lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponível"
javaExecutableTitle = "Executável Java"
javaExecSelDialogTitle = "Selecionar Executável Java"
javaExecSelButtonText = "Escolher Arquivo"
javaExecDesc = "O executável Java é validado antes do lançamento do jogo."
javaPathDesc = "O caminho deve terminar com <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opções Adicionais da JVM"
jvmOptsDesc = "Opções a serem fornecidas para a JVM em tempo de execução. <em>-Xms</em> e <em>-Xmx</em> não devem ser incluídas."
launcherTabHeaderText = "Configurações do Launcher"
launcherTabHeaderDesc = "Opções relacionadas ao próprio launcher."
allowPrereleaseTitle = "Permitir Atualizações de Pré-Lançamento."
allowPrereleaseDesc = "Pré-Lançamentos incluem novos recursos que podem não ter sido totalmente testados ou integrados.<br>Isso sempre será verdadeiro se você estiver usando uma versão de pré-lançamento."
dataDirectoryTitle = "Diretório de Dados"
selectDataDirectory = "Selecionar Diretório de Dados"
chooseFolder = "Escolher Pasta"
dataDirectoryDesc = "Todos os arquivos do jogo e instalações locais do Java serão armazenados no diretório de dados.<br>Capturas de tela e salvamentos de mundos são armazenados na pasta da instância para a configuração do servidor correspondente."
aboutTabHeaderText = "Sobre"
aboutTabHeaderDesc = "Ver informações e notas de lançamento para a versão atual."
aboutTitle = "{appName}"
stableRelease = "Lançamento Estável"
versionText = "Versão "
sourceGithub = "Fonte (GitHub)"
support = "Suporte"
devToolsConsole = "Console DevTools"
releaseNotes = "Notas de Lançamento"
changelog = "Registro de Alterações"
noReleaseNotes = "Sem Notas de Lançamento"
viewReleaseNotes = "Ver Notas de Lançamento no GitHub"
launcherUpdatesHeaderText = "Atualizações do Launcher"
launcherUpdatesHeaderDesc = "Baixe, instale e revise as atualizações do launcher."
checkForUpdates = "Verificar Atualizações"
whatsNew = "O Que Há de Novo"
updateReleaseNotes = "Atualizar Notas de Lançamento"

[ejs.waiting]
waitingText = "Esperando pela Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"


[js.discord]
waiting = "Esperando pelo Cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Login Microsoft"
microsoftLogoutTitle = "Logout Microsoft"

[js.login]
login = "LOGIN"
loggingIn = "LOGANDO"
success = "SUCESSO"
tryAgain = "Tente Novamente"

[js.login.error]
invalidValue = "* Valor Inválido"
requiredValue = "* Requerido"

[js.login.error.unknown]
title = "Erro Desconhecido Durante o Login"
desc = "Ocorreu um erro desconhecido. Por favor, veja o console para mais detalhes."

[js.landing.launch]
pleaseWait = "Por favor, espere.."
failureTitle = "Erro Durante o Lançamento"
failureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
okay = "Ok"

[js.landing.selectedAccount]
noAccountSelected = "Nenhuma Conta Selecionada"

[js.landing.selectedServer]
noSelection = "Nenhum Servidor Selecionado"
loading = "Carregando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFFLINE"
players = "JOGADORES"

[js.landing.systemScan]
checking = "Verificando informações do sistema.."
noCompatibleJava = "Nenhuma Instalação<br>Compatível de Java Encontrada"
installJavaMessage = "Para iniciar o Minecraft, você precisa de uma instalação de 64 bits do Java {major}. Gostaria que instalássemos uma cópia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando Download do Java.."
javaDownloadFailureTitle = "Erro Durante o Download do Java"
javaDownloadFailureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
javaRequired = "Java é Necessário<br>para Iniciar"
javaRequiredMessage = 'Uma instalação válida de Java {major} x64 é necessária para iniciar.<br><br>Por favor, consulte nosso <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guia de Gerenciamento de Java</a> para instruções sobre como instalar o Java manualmente.'
javaRequiredDismiss = "Eu Entendo"
javaRequiredCancel = "Voltar"

[js.landing.downloadJava]
findJdkFailure = "Falha ao encontrar a distribuição OpenJDK."
javaDownloadCorruptedError = "O JDK baixado tem um hash incorreto, o arquivo pode estar corrompido."
extractingJava = "Extraindo Java"
javaInstalled = "Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Carregando informações do servidor.."
fatalError = "Erro Fatal"
unableToLoadDistributionIndex = "Não foi possível carregar uma cópia do índice de distribuição. Veja o console (CTRL + Shift + i) para mais detalhes."
pleaseWait = "Por favor, espere.."
errorDuringLaunchTitle = "Erro Durante o Lançamento"
seeConsoleForDetails = "Veja o console (CTRL + Shift + i) para mais detalhes."
validatingFileIntegrity = "Validando integridade dos arquivos.."
errorDuringFileVerificationTitle = "Erro Durante a Verificação dos Arquivos"
downloadingFiles = "Baixando arquivos.."
errorDuringFileDownloadTitle = "Erro Durante o Download dos Arquivos"
preparingToLaunch = "Preparando para iniciar.."
launchingGame = "Iniciando jogo.."
launchWrapperNotDownloaded = "O arquivo principal, LaunchWrapper, não foi baixado corretamente. Como resultado, o jogo não pode ser iniciado.<br><br>Para corrigir esse problema, desative temporariamente seu software antivírus e inicie o jogo novamente.<br><br>Se tiver tempo, por favor <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">envie um problema</a> e nos informe qual software antivírus você usa. Entraremos em contato com eles e tentaremos resolver isso."
doneEnjoyServer = "Pronto. Aproveite o servidor!"
checkConsoleForDetails = "Por favor, verifique o console (CTRL + Shift + i) para mais detalhes."

[js.landing.news]
checking = "Verificando Notícias"

[js.landing.discord]
loading = "Carregando jogo.."
joining = "Navegando para Westeros!"
joined = "Explorando o Reino!"

[js.overlay]
dismiss = "Dispensar"

[js.settings.fileSelectors]
executables = "Executáveis"
allFiles = "Todos os Arquivos"

[js.settings.mstfLogin]
errorTitle = "Algo Deu Errado"
errorMessage = "A autenticação da Microsoft falhou. Por favor, tente novamente."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Algo Deu Errado"
errorMessage = "O logout da Microsoft falhou. Por favor, tente novamente."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Selecionar Conta"
selectedButton = "Conta Selecionada &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Aviso<br>Esta é Sua Última Conta"
lastAccountWarningMessage = "Para usar o launcher, você deve estar logado em pelo menos uma conta. Você precisará fazer login novamente depois.<br><br>Tem certeza de que deseja sair?"
confirmButton = "Tenho Certeza"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nome de Usuário"
uuid = "UUID"
selectAccount = "Selecionar Conta"
selectedAccount = "Conta Selecionada ✓"
logout = "Sair"

[js.settings.dropinMods]
removeButton = "Remover"
deleteFailedTitle = "Falha ao Excluir<br>Mod Drop-in {fullName}"
deleteFailedMessage = "Certifique-se de que o arquivo não está em uso e tente novamente."
failedToggleTitle = "Falha ao Alternar<br>Um ou Mais Mods Drop-in"
okButton = "Ok"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Selecionado: Java {version} ({vendor})"
invalidSelection = "Seleção Inválida"
requiresJava = "Requer Java {major} x64."
availableOptions = "Opções Disponíveis para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-lançamento"
stableReleaseTitle = "Lançamento Estável"
releaseNotesFailed = "Falha ao carregar as notas de lançamento."

[js.settings.updates]
newReleaseTitle = "Nova Versão Disponível"
newPreReleaseTitle = "Nova Pré-lançamento Disponível"
downloadingButton = "Baixando.."
downloadButton = 'Baixar do GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Feche o launcher e execute o dmg para atualizar.</span>'
latestVersionTitle = "Você Está Usando a Versão Mais Recente"
checkForUpdatesButton = "Verificar Atualizações"
checkingForUpdatesButton = "Verificando Atualizações.."

[js.settings.msftLogin]
errorTitle = "Falha no Login da Microsoft"
errorMessage = "Não foi possível autenticar sua conta Microsoft. Por favor, tente novamente."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erro Fatal: Não Foi Possível Carregar o Índice de Distribuição"
fatalErrorMessage = "Não foi possível estabelecer uma conexão com nossos servidores para baixar o índice de distribuição. Nenhuma cópia local estava disponível para carregar. <br><br>O índice de distribuição é um arquivo essencial que fornece as informações mais recentes do servidor. O launcher não pode iniciar sem ele. Certifique-se de que está conectado à internet e reinicie o aplicativo."
closeButton = "Fechar"

[js.uibinder.validateAccount]
failedMessageTitle = "Falha ao Atualizar Login"
failedMessage = "Não foi possível atualizar o login para <strong>{account}</strong>. Por favor, selecione outra conta ou faça login novamente."
failedMessageSelectAnotherAccount = "Não foi possível atualizar o login para <strong>{account}</strong>. Por favor, faça login novamente."
loginButton = "Login"
selectAnotherAccountButton = "Selecionar Outra Conta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Verificando Atualizações..."
installNowButton = "Instalar Agora"
checkForUpdatesButton = "Verificar Atualizações"

[js.auth.microsoft.error]
noProfileTitle = "Erro Durante o Login:<br>Perfil Não Configurado"
noProfileDesc = "Sua conta Microsoft ainda não tem um perfil do Minecraft configurado. Se você comprou o jogo recentemente ou resgatou através do Xbox Game Pass, você precisa configurar seu perfil em <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Se você ainda não comprou o jogo, também pode fazer isso em <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erro Durante o Login:<br>Sem Conta Xbox"
noXboxAccountDesc = "Sua conta Microsoft não tem uma conta Xbox associada."
xblBannedTitle = "Erro Durante o Login:<br>Xbox Live Indisponível"
xblBannedDesc = "Sua conta Microsoft é de um país onde o Xbox Live não está disponível ou está banido."
under18Title = "Erro Durante o Login:<br>Aprovação dos Pais Necessária"
under18Desc = "Contas de usuários menores de 18 anos devem ser adicionadas a uma Família por um adulto."
unknownTitle = "Erro Desconhecido Durante o Login"
unknownDesc = "Ocorreu um erro desconhecido. Por favor, veja o console para mais detalhes."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erro Interno:<br>Método Não Permitido"
methodNotAllowedDesc = "Método não permitido. Por favor, reporte este erro."
notFoundTitle = "Erro Interno:<br>Não Encontrado"
notFoundDesc = "O endpoint de autenticação não foi encontrado. Por favor, reporte este problema."
accountMigratedTitle = "Erro Durante o Login:<br>Conta Migrada"
accountMigratedDesc = "Você tentou fazer login com uma conta migrada. Tente novamente usando o e-mail da conta como nome de usuário."
invalidCredentialsTitle = "Erro Durante o Login:<br>Credenciais Inválidas"
invalidCredentialsDesc = "O e-mail ou senha que você inseriu está incorreto. Por favor, tente novamente."
tooManyAttemptsTitle = "Erro Durante o Login:<br>Muitas Tentativas"
tooManyAttemptsDesc = "Houve muitas tentativas de login com esta conta recentemente. Por favor, tente novamente mais tarde."
invalidTokenTitle = "Erro Durante o Login:<br>Token Inválido"
invalidTokenDesc = "O token de acesso fornecido é inválido."
tokenHasProfileTitle = "Erro Durante o Login:<br>Token Tem Perfil"
tokenHasProfileDesc = "O token de acesso já tem um perfil atribuído. A seleção de perfis ainda não foi implementada."
credentialsMissingTitle = "Erro Durante o Login:<br>Credenciais Ausentes"
credentialsMissingDesc = "Nome de usuário/senha não foi enviado ou a senha tem menos de 3 caracteres."
invalidSaltVersionTitle = "Erro Durante o Login:<br>Versão de Sal Inválida"
invalidSaltVersionDesc = "Versão de sal inválida."
unsupportedMediaTypeTitle = "Erro Interno:<br>Tipo de Mídia Não Suportado"
unsupportedMediaTypeDesc = "Tipo de mídia não suportado. Por favor, reporte este erro."
accountGoneTitle = "Erro Durante o Login:<br>Conta Migrada"
accountGoneDesc = "A conta foi migrada para uma conta Microsoft. Por favor, faça login com a Microsoft."
unreachableTitle = "Erro Durante o Login:<br>Inacessível"
unreachableDesc = "Não foi possível alcançar os servidores de autenticação. Certifique-se de que estão online e que você está conectado à internet."
gameNotPurchasedTitle = "Erro Durante o Login:<br>Jogo Não Comprado"
gameNotPurchasedDesc = "A conta que você está tentando fazer login não comprou uma cópia do Minecraft. Você pode comprar uma cópia em <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erro Desconhecido Durante o Login"
unknownErrorDesc = "Ocorreu um erro desconhecido. Por favor, veja o console para mais detalhes."
